### ISSUE TITLE
Add support for Optimistic Execution to Octane

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#1401]
CosmosSDK has a feature called "[Optimistic Execution](https://medium.com/the-interchain-foundation/optimistic-execution-landing-in-the-cosmos-sdk-a28fc72af650)". 

Octane doesn't support it at this point. It results in reorgs both normal and "impossible", resulting in the chain stalling.

Adding support for OE would result in:
 - Faster block times
 - Hardened EngineAPI
 
 The re-orgs are pointing to possible bugs or race conditions in current implementation that just isn't triggered due to non OE timing.

**Comment by arajasek** [comment]
I looked into this in depth today. The problem is that as part of the Optimistic Execution flow in Cosmos, we are making a state update to the geth client (specifically, we are updating our canonical and finalized blocks). Because this can happen on unfinalized state (optimistically), geth gets confused and starts to fail all state updates, since it looks like a finalized block is being reorged out. 

Digging deeper (exec trace below), this is happening because one of the txs in the Cosmos Optimistic Execution leads to a [runMsgs](https://github.com/cosmos/cosmos-sdk/blob/1bbb499cdf32dbf2bed3607860c30693c3f5674a/baseapp/baseapp.go#L955) query that hits up our `msgServer`'s `ExecutionPayload` method ([here](https://github.com/omni-network/omni/blob/0808374784bc369301b3db36dbb72011c1668642/octane/evmengine/keeper/msg_server.go#L231)). Note that this is the stateful implementation of this method that calls geth's `ForkchoiceUpdatedV3` method to update the chain, NOT the read-only `proposalServer` that only validates input. 

Unfortunately, I'm not sure what this tx is and what exactly the bug is, so I don't have a fix in mind yet. It seems wrong for the optimistic workflow to call any stateful method. However, whether the problem is that Halo is providing a stateful endpoint here (and should instead provide the read-only version), or whether the problem is that such a tx shouldn't be happening at all is unclear to me.

---

Exec trace:

```
2024-07-07 19:54:23.296	time=2024-07-07T23:54:23.135Z level=WARN 
source=/home/runner/work/omni/omni/octane/evmengine/keeper/msg_server.go:69 
msg="Processing finalized payload failed: evm fork choice update (will retry)" status="" err="rpc forkchoice updated v3: Invalid forkchoice state" stacktrace="
github.com/omni-network/omni/lib/errors.Wrap
/home/runner/work/omni/omni/lib/errors/errors.go:39
github.com/omni-network/omni/lib/ethclient.engineClient.ForkchoiceUpdatedV3
/home/runner/work/omni/omni/lib/ethclient/engineclient.go:136
github.com/omni-network/omni/octane/evmengine/keeper.msgServer.ExecutionPayload.func2
/home/runner/work/omni/omni/octane/evmengine/keeper/msg_server.go:66
github.com/omni-network/omni/octane/evmengine/keeper.retryForever
/home/runner/work/omni/omni/octane/evmengine/keeper/helpers.go:25
github.com/omni-network/omni/octane/evmengine/keeper.msgServer.ExecutionPayload
/home/runner/work/omni/omni/octane/evmengine/keeper/msg_server.go:65
github.com/omni-network/omni/octane/evmengine/types._MsgService_ExecutionPayload_Handler.func1
/home/runner/work/omni/omni/octane/evmengine/types/tx.pb.go:338
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).registerMsgServiceHandler.func2.1
/home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.7/baseapp/msg_service_router.go:175
github.com/omni-network/omni/octane/evmengine/types._MsgService_ExecutionPayload_Handler
/home/runner/work/omni/omni/octane/evmengine/types/tx.pb.go:340
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).registerMsgServiceHandler.func2
/home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.7/baseapp/msg_service_router.go:198
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs
/home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.7/baseapp/baseapp.go:1015
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx
/home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.7/baseapp/baseapp.go:953
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).deliverTx
/home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.7/baseapp/baseapp.go:762
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).internalFinalizeBlock
/home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.7/baseapp/abci.go:790
github.com/cosmos/cosmos-sdk/baseapp/oe.(*OptimisticExecution).Execute.func1
/home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.7/baseapp/oe/optimistic_execution.go:108
runtime.goexit
/opt/hostedtoolcache/go/1.22.5/x64/src/runtime/asm_amd64.s:1695"
```

**Comment by arajasek** [comment]
@corverroos dug into the latencies of the two operations involved in Optimistic Execution:

- `ProcessProposal`, which runs anyway, takes 50-75ms
- `FinalizeBlock`, which usually runs only when the block is actually finalized, takes 20ms and marks blocks in geth as finalized

The conclusion is that using Optimistic Execution doesn't win us all that much, and is dangerous for how we use geth. I think we just say we don't use OE.
