### ISSUE TITLE
Fix - xsubmit fails on xmsg to zero addr

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#1437]

**Comment by kevinhalliday** [comment]
These fail because we set `VirtualPortalAddress` to `address(0)`, which signals an syscall. Syscalls are functions called on the portal itself. These do not have gas limits. For this reason, to ensure relayers do not gas grief submissions, and cause them to run out of gas before completing, we require that syscalls do not revert, rather than letting them fail and emitting a failed receipt. It's also good to fail loudly with syscall failures, as that would signal a larger problem.
