### ISSUE TITLE
Valsync pre-buffer upgrade: ADR

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#1857]
#### Problem to Solve
The `valsync` module currently buffers and attests to validator set upgrades POST staking module changes and PRE cometBFT changes.

This means that any validator set upgrade (create-validator, delegate, undelegate, slash) all result in validator set upgrades as these messages are delivered. This is normal to cosmosSDK.

Omni however needs to delliver validator set upgrades to all EVM changes which costs money. We also have the risk in portal contracts that only the last 10 validator sets are allowed to submit messages. So in the event that 10 valset updates occur while one shard is lagging, that shard could get stuck.

The valsync equivocation window issue is also due to POST staking buffer.

#### Proposed Solution
Buffering staking messages PRE staking module and only submitting them one per period (e.g. once per day) solves these problems.

- Buffer staking evm event logs in the valsync module state
- Once per period (X Blocks), calcualte the resulting validator set of applying those messages (discarding DB changes)
- Create an unattested validator set
- Once it is attested, then only apply the messages on the staking module

> Note an ADR and nework-upgrade is required

**Comment by chmllr** [comment]
After a design discussion we decide to descope the reordering of the event processing due to the complexity that arises from the fact that in the time between we created a new validator set from buffered logs and the time where we need to pass these logs on to the staking module, some validator changes (like slashing) might have occured and need to be taking into the account. We might revisit this in the future, but for now, we keep this issue focused on reducing the portal updates via buffering.
