### ISSUE TITLE
Verify mainnet contracts

### ISSUE THREAD

**Issue by ttarsi** [omni-network/omni#2266]
#### Problem to Solve

mainnet contracts are deployed but unverified, including portals and fee oracles (maybe missing some) on all supported chains.

#### Proposed Solution

verify them!

**Comment by Zodomo** [comment]
I am trying to verify the OmniPortal and FeeOracleV1 contracts on Ethereum mainnet and it is not working.

When attempting via the Etherscan web GUI:
- Set compiler type to Standard-Json-Input
- Set compiler version to 0.8.24
- Set license to GNU GPL V3
- Provide JSON generated by `forge verify-contract --show-standard-json-input 0x5e9A8Aa213C912Bf54C86bf64aDB8ed6A79C04d1 OmniPortal`
- Get "Error! Unable to generate Contract Bytecode and ABI"

When attempting via Foundry's forge-verify utility:
- Run `forge verify-contract --etherscan-api-key ${ETHERSCAN_API_KEY} --rpc-url https://eth.llamarpc.com 0x5e9A8Aa213C912Bf54C86bf64aDB8ed6A79C04d1 OmniPortal`
- Get ![Image](https://github.com/user-attachments/assets/143bb45e-9b32-431b-93f8-f97ae3204894)
- See contract is still unverified https://etherscan.io/address/0x5e9a8aa213c912bf54c86bf64adb8ed6a79c04d1#code

I've also attempted this with the FeeOracleV1 contract at 0xd27dF544777BEb6635590035D69f72Cc1F066E7d.

Can anyone else attempt this and see if their results are similar? We may need to upgrade foundry versions in order to accommodate changes in Etherscan's verification API, however I am unsure as to why it is failing via the GUI as well.

I have also reached out to them on X here: https://x.com/0xZodomo/status/1849850743349743706
